### ISSUE TITLE
Crashes on Linux 

### ISSUE THREAD

**Issue by CyberSaintPlaysRL** [SpeedReflect/Binary#14]
parameterbDPI_AWARENESS_CONTEXT_UNSPECIFIED when i press main in modder

**Comment by AvinashReddy3108** [comment]
Same here, I've got some lines from the `MainLog.txt` file to help debug.

```text
Binary : Unknown Exception
05/14/2023 20:48
--------------------------
Exception: dpiContext (Parameter 'DPI_AWARENESS_CONTEXT_UNSPECIFIED')
HResult: -2147024809
StackTrace:    at System.Windows.Forms.CommonUnsafeNativeMethods.TrySetThreadDpiAwarenessContext(DpiAwarenessContext dpiContext)
   at System.Windows.Forms.DpiHelper.DpiAwarenessScope.Dispose()
   at System.Windows.Forms.ToolStripManager.ModalMenuFilter.PreFilterMessage(Message& m)
   at System.Windows.Forms.Application.ThreadContext.ProcessFilters(MSG& msg, Boolean& modified)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FPreTranslateMessage(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.RunDialog(Form form)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at System.Windows.Forms.Form.ShowDialog()
   at Binary.IntroUI.ModderInteract()
   at Binary.IntroUI.IntroPictureModder_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
TargetSite: System.Windows.Forms.DpiAwarenessContext TrySetThreadDpiAwarenessContext(System.Windows.Forms.DpiAwarenessContext)
Source: System.Windows.Forms
```

**Comment by xrtxn** [comment]
I use bottles, I switched the wine version to windows 7 and it works correctly.

**Comment by AvinashReddy3108** [comment]
> I use bottles, I switched to windows 7 and it works correctly.

You mean you have set the "Windows version" setting in your bottle to Windows 7, right?

_PS: for vanilla WINE, you can use the `winecfg` to set the Windows version of your prefix._
![Screenshot_20230719_084520](https://github.com/SpeedReflect/Binary/assets/27774996/e108dbf6-7be9-4bf9-97af-b88f1da36076)

Will test this out, hope this works for me as it has done for you..

**Comment by xrtxn** [comment]
> You mean you have set the "Windows version" setting in your bottle to Windows 7, right?

yes, sorry for not being clear

**Comment by AvinashReddy3108** [comment]
Sorry for being (extremely) late, but I just want to let everyone know that setting the "Windows version" of the WINE prefix to "Windows 7" fixes this issue..

![Screenshot_20230801_164043](https://github.com/SpeedReflect/Binary/assets/27774996/a6ef602f-1628-4d84-be7e-e251edbcbf1c)

Read [this](https://github.com/SpeedReflect/Binary/issues/14#issuecomment-1641351582) on how to do it..
